import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import "bootstrap/dist/css/bootstrap.min.css";
import "bootstrap-icons/font/bootstrap-icons.css";
import ClientBootstrap from "@/components/ClientBootstrap";
import Sidebar from "@/components/Sidebar";
import ToastArea from "@/components/ToastArea";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <ClientBootstrap />
        <div className="d-flex" style={{ minHeight: "100vh" }}>
          <Sidebar />
          <main className="flex-grow-1">
            <div className="container py-3">{children}</div>
          </main>
        </div>
        <ToastArea />
      </body>
    </html>
  );
}
